### ISSUE TITLE
user should have option to be emailed their product for purchasing later

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/ai-print-shop#18]

**Comment by Bilalm354** [comment]
So customers should get an email for each prompt they make with a link to the product for that image. This way they could be more likely to buy later and they could also go back and see one of the images they had so that it's not lost.

**Comment by haffi96** [comment]
> So customers should get an email for each prompt they make with a link to the product for that image. This way they could be more likely to buy later and they could also go back and see one of the images they had so that it's not lost.

Will we have their email if they just got to the website and entered prompt?

**Comment by Bilalm354** [comment]
> > So customers should get an email for each prompt they make with a link to the product for that image. This way they could be more likely to buy later and they could also go back and see one of the images they had so that it's not lost.
> 
> Will we have their email if they just got to the website and entered prompt?

Not rn we don't
