### ISSUE TITLE
vercel deployment getting cancelled on PR

### ISSUE THREAD

**Issue by haffi96** [bilal-and-haffi/ai-print-shop#181]

**Comment by Bilalm354** [comment]
It usually says cancelled immediately but if you check a minute later it builds

**Comment by Bilalm354** [comment]
Also could this be to do with neon? Like neon cancelling the deploy to get preview env variables and then restarting it? Idk. I didn't set it up so not sure how it's set up but feel like have seen on the verve website that when you use db branching vercel does a deploy then cancel then deploy again

**Comment by haffi96** [comment]
makes sense, ill cancel this if not happening after paying for neon
