### ISSUE TITLE
The copyright alert lets you continue

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/ai-print-shop#210]
Probs shouldn't

**Comment by haffi96** [comment]
If its legally possible to let them continue at their own risk or something

like 'By continue you're agree to terms & conditions' or something

**Comment by Bilalm354** [comment]
I think main likely consequence is that printify would ban our account

**Comment by Bilalm354** [comment]
added a message saying that we might cancel the order if they continue
