### ISSUE TITLE
Icons don't show on safari tabs or when sending links on iMessage or WhatsApp

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/ai-print-shop#211]
![image](https://github.com/user-attachments/assets/d9130672-e69e-4df3-abb2-6b3718ff998c)

**Comment by haffi96** [comment]
im confused. Whats the problem?

Which icon? 

The icon at the top of the tab is the app icon no?

**Comment by Bilalm354** [comment]
@haffi96 on safari there's no icon next to the name there ![image](https://github.com/user-attachments/assets/c69581a5-6d4f-4a63-9f05-ec356bc33e56)

And no icon when saving as bookmark (top left)

![image](https://github.com/user-attachments/assets/0ab297a8-34b3-4ace-8333-361107632bc9)

V unimportant but bothered me

**Comment by Bilalm354** [comment]
The icon under the tab is missing like you can see on Amazon or YouTube tabs

**Comment by Bilalm354** [comment]
![image](https://github.com/user-attachments/assets/37d8ed5c-3b37-4c46-8cb8-f43ac0177d03)

**Comment by Bilalm354** [comment]
Icon is there. Maybe you fixed or something I changed worked but had delay due to caching on vercel or phone @haffi96

**Comment by haffi96** [comment]
I didn't do shit
