### ISSUE TITLE
Should be able to leave 'Style' and 'Location' as undefine or None

### ISSUE THREAD

**Issue by haffi96** [bilal-and-haffi/ai-print-shop#215]

**Comment by haffi96** [comment]
@Bilalm354 thoughts?

**Comment by Bilalm354** [comment]
AgreeOn 18 Jul 2024, at 12:10, Haffi Mazhar ***@***.***> wrote:﻿
@Bilalm354 thoughts?

**Comment by Bilalm354** [comment]
Agree

Or should have an other/ text box option
