### ISSUE TITLE
Add vercel tracker to error page

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/ai-print-shop#333]

**Comment by Bilalm354** [comment]
And an email to me

**Comment by haffi96** [comment]
which error page? All of them?

**Comment by haffi96** [comment]
also for alerting, we might need to use something else. Checked but couldn't find an alerting thing by Vercel itself.

Theres some logging integrations that might work. 

i.e https://vercel.com/integrations/axiom 

It's basically another place for the logs to go but you can setup a specifi log monitor

i.e if there is more than X Error log: "Something went wrong" in a few minutes, send email

**Comment by haffi96** [comment]
Already added in https://github.com/bilal-and-haffi/ai-print-shop/commit/6c92b2bca1a9f3661c2687ead0d8a20bddaafaee

**Comment by haffi96** [comment]
Added axiom integration and monitor

![image](https://github.com/user-attachments/assets/58f62cb9-37ab-4b8a-82c1-8b843234fbc0)

and it runs every 15 minutes, sends email if more than 50 error logs found in 15 mins
