### ISSUE TITLE
setup stripe prod

### ISSUE THREAD

**Issue by haffi96** [bilal-and-haffi/ai-print-shop#89]
- [x] update vercel production env with stripe secrets
- [x] setup stripe prod webhook
- [x] setup user emails
- [x] tax collection stuff
- [x] a real payment should get to your order has been processed screen

**Comment by Bilalm354** [comment]
@haffi96 can you do this plz?

**Comment by Bilalm354** [comment]
@haffi96 

user emails? 

tax collection stuff?

**Comment by haffi96** [comment]
already enabled the emails I think. Its like stripe sends an automated email for payments
![image](https://github.com/bilal-and-haffi/ai-print-shop/assets/53666594/c32d43e0-a59c-48ff-a62b-ed9e7a074aa8)


tax collection stuff...I think we already enabled automatic tax, so basically get stripe to do something for tax so we don't have to collect tax ids from customers (good enough for now) https://github.com/bilal-and-haffi/ai-print-shop/blob/d4985b1efa563349a842031ff253b7930c8e85cb/lib/stripe/service.ts#L90
