### ISSUE TITLE
Order success page hangs on branch previews

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/ai-print-shop#98]
<img width="1342" alt="image" src="https://github.com/bilal-and-haffi/aiPersonalisedGifts/assets/53113053/954a6d75-5f1e-45e7-9682-2ab868982da0">

My guess is that the correct orderdb isn't populated. maybe the neon branches aren't working correctly. not sure.

**Comment by haffi96** [comment]
I think it's cause the stripe webhook can only have a single url configured

We either need a static preview builds url or figure out how to update the stripe webhook url for each branch
